# define a list of strings - 2023 events
events_23 = ["Alex Python Promotes Vegan Business on Social Media",
             "Brendan Murray Posts Another Medium Tattoo He Gets",
             "Cassie Constable Gets Pregnant (again)",
             "Mike Cubello Fitness Vlog",
             "Greg Contacts Fiona",
             "Jack Canova/Child Girlfriend Breakup",
             "Katie Mozes/Joe Bintz Finally Breakup",
             "Lila Gets Engaged",
             "Lila Moves To Utah",
             "Lila/Sean Breakup",
             "Maeve Finds a Man Worth her Time",
             "Maridith Bangs A Man",
             "Mikey Grogan Does Something Insane Again",
             "Mike Cubello Fit Pic Post",
             "Literally Anyone Sees Will Anderson In Person",
             "Nate/Rozara Have A Baby (again)",
             "Nick/Holly Get Engaged",
             "Nora Sheehan Gets Engaged",
             "Phoebe Accidentally Homewrecks Again",
             "Shannon Howland/Trevor Kniffin Engagement",
             "Sofia Leaves the Country and Tells No One",
             "Someone From Bethlehem Is Working At The Delmar Beverage Center",
             "Someone From HS Promotes A Pyramid Scheme",
             "Keegan Guinn/Shelby Fichter Divorce",
             "Keegan Guinn/Shelby Fichter Have A Child",
             "Nora Salo Queerbaits",
             "Emily Kroez Posts Extreme No Ass",
             "Someone From High School Debuts Ugly Boyfriend",
             "Aidan Sheehan/Claire Yates Engagement",
             "Devlin/Alyssa Get Engaged",
             "Nate Brands gets New Awful Girlfriend",
             "Someone from Highschool is Suddenly Religious",
             "Sam Lee/Boyfriend Breakup",
             "Grace Morris Posts Gay Shit About Best Friend And NOT Her Girlfriend",
             "Anna Sanzone Posts in a Sports Arena",
             "Someone in Immediate Friend Group has STD Scare",
             "Caroline Robinson/ Brendan Callucio Engagement",
             "Isa Posts To Promote Her Music",
             "Black Anna Sanzone Places In A Bodybuilding Show",
             "Mr. Fris Gets In Legal Trouble Again",
             "Christian Asks Fiona Another Weird Question About The Past",
             "We Find Out Someone From High School Is Gay",
             "White Anna Sanzone Finally Dates The Guido Of Her Dreams",
             "Ryan Vadney Proposes",
             "Gillian Newborn Gets Engaged",
             "Morgan Gillies/Cooper Szelest Engagement",
             "Someone From HS Pops Up on One of our TikTok Feeds",
             "Narker Contacts Julia",
             "Hani Reveals Something Deeply Personal",
             "Phoebe Settles Down",
             "Anna Biganne Comes Out",
             "A Man From High School Debuts A New Mustache",
             "Julia Finds A Man Worth Her Time",
             "Victoia Knack/Tim Blake Pregnant (again)",
             "Caroline Robinson/Brendan Callucio Breakup",
             "Pat Contacts Steph OR Maddie",
             "Liam Barber and Emily Worth Breakup",
             "Hani Posts Something Problematic",
             "Chris Abbey Posts Something Problematic",
             "Anyone Speaks to Matt Jonas",
             "Maddie Pezze/Jon Hogg Breakup",
             "Nanaka and Jesus Looking Boyfriend Engagement",
             "Geoff Contacts Julia Again",
             "One of Us Quit our Job",
             "Lauren Wildermuth Posts A Pic Looking Exceedingly Orange",
             "Someone in Immediate Friend Group as Pregnancy Scare",
             "Hani Gets Engaged",
             "Julia Moves Again",
             "Keegan Guinn Calls Fiona",
             "Kevin Mulhall Proposes To Girlfriend",
             "Kim Granito Gay Wedding",
             "Jack Sheraw/Kenzie Jack Pregnant (again)",
             "Jess Cronin/Ainsley Broderick's Brother Engaged",
             "Joe Bintz/Katie Mozes Engagement",
             "Dez Sleeps With A Woman",
             "Emma Cremo/Andrew Woods Breakup",
             "Emma Cremo/Andrew Woods Engagement",
             "Mike Cubello Posts About a Celeb like He Knows Them",
             "Catherine Harvey Pregnancy Announcement",
             "Maddie Pezze/Jon Hogg Get Engaged",
             "Brent Hayward/Katie Wentworth Get Married",
             "Brynn Rask Instagram Vlog",
             "Liam Barber Posts New Bad Tattoo",
             "Zach Libby Returns to New York State",
             "Alyssa Viggiano Gets Engaged",
             "Amy Barba Gay Engagement",
             "Anna Barnet/Weird BF Get Engaged",
             "One of us Sees A Delmar Parent at O'Slatts",
             "A Group Of 5+ Boys We Went To School With Are Photographed Together",
             "A Homer Gets Engaged",
             "A Homer Has A Kid",
             "Catherine Harvey Posts Pic with Bigoted Aura"
            ]

# print the list of strings
print(events_23)

# loop over the names list, and
# print each string one at a time
#for event in events_23:
#     print(events_23)

# add a name to the list
#events_23.append()